package _02_spring_on_the_web._05_building_spring_web_applications._02_writing_a_simple_controller._02_defining_class_level_request_handling;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan(basePackages = {"_02_spring_on_the_web._05_building_spring_web_applications._02_writing_a_simple_controller._02_defining_class_level_request_handling"})
public class RootConfig {
}
