package _01_core_spring._02_wiring_beans._02_automatically_wiring_beans._01_creating_discoverable_beans.listing_02_01_02_03_java_component_scanning;

import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan
public class CDPlayerConfig {}
